Player status GUI now functional
LimaInc/SustainableCraft pull request #48
Opened 2018-02-08 15:00 UTC by DazKins

2018-02-08 18:09 UTC, JamesHinshelwood requested changes

2018-02-08 18:09 UTC, JamesHinshelwood commented on Scripts/Player.cs
> +    public float GetCurrentAir()
Can we use properties for these to keep consistency with the rest of the code. e.g. public float CurrentAir { get; set; } or something

2018-02-08 18:09 UTC, JamesHinshelwood commented on Scripts/Player.cs
> +    public float GetCurrentAir()
Also, getting this error
![image](https://user-images.githubusercontent.com/11905377/35990141-135aba54-0cfb-11e8-824f-451855e8386f.png)

2018-02-08 18:46 UTC, DazKins commented
I'll be honest, I don't see the point of using the properties much in C#, surely it just makes code within the class really messy because of the getters and setters, this feels like a much more natural way to do things. The error is due to some parts of the code, trying to remove a child from a node that is null, this is fine and will not cause the code to crash but I will add some null checks

2018-02-08 18:50 UTC, DazKins commented
Just found another bug with the inventory screen, so don't merge plz

2018-02-08 21:17 UTC, JamesHinshelwood commented
They make the interface of the class much cleaner to use. You don't need loads of GetVariable SetVariable functions, you can just use the variable

2018-02-09 13:49 UTC, JamesHinshelwood approved these changes
Nice work!

2018-02-09 13:50 UTC, merged

2018-02-16 12:11 UTC, JamesHinshelwood commented
Closes #16