Animals
LimaInc/SustainableCraft pull request #78
Opened 2018-02-28 22:27 UTC by sjtsilvester

2018-02-28 22:36 UTC, AdamSKucz commented
For me godot refuses to even open it

![image](https://user-images.githubusercontent.com/17096872/36817086-d4988aac-1cd7-11e8-859d-258f8e361f20.png)

2018-02-28 23:42 UTC, JamesHinshelwood requested changes
Please stick to the convention of using lowercase for file extensions. These are not case sensitive on Windows, but are on Linux (not sure about MacOS), so we should stick to a standard format of all lower case. I currently get an error loading itemanimalfossil.png, because it is named as .PNG in the files.

2018-02-28 23:45 UTC, AdamSKucz commented
Oops, that's actually my fault, I didn't pay attention when saving it and must have used a different program.

2018-03-01 14:34 UTC, JamesHinshelwood approved these changes

2018-03-01 14:34 UTC, merged